// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvadviaakpynpldmkhtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12YWR2aWFha3B5bnBsZG1raHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTI0OTcsImV4cCI6MjA2MjUyODQ5N30.ydnpWeqBOjNaiqkYYeIsIG5MXe95zZ_ObBd9cPHCdBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);